// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	types "github.com/cosmos/cosmos-sdk/types"
	mock "github.com/stretchr/testify/mock"
)

// DistributionKeeper is an autogenerated mock type for the DistributionKeeper type
type DistributionKeeper struct {
	mock.Mock
}

// GetPreviousProposerConsAddr provides a mock function with given fields: ctx
func (_m *DistributionKeeper) GetPreviousProposerConsAddr(ctx types.Context) types.ConsAddress {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousProposerConsAddr")
	}

	var r0 types.ConsAddress
	if rf, ok := ret.Get(0).(func(types.Context) types.ConsAddress); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.ConsAddress)
		}
	}

	return r0
}

// NewDistributionKeeper creates a new instance of DistributionKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDistributionKeeper(t interface {
	mock.TestingT
	Cleanup(func())
},
) *DistributionKeeper {
	mock := &DistributionKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
