<<<<<<< HEAD
// Code generated by mockery v2.40.1. DO NOT EDIT.
=======
// Code generated by mockery v2.43.2. DO NOT EDIT.
>>>>>>> f1cde2a (fix: mempool lane size check on `CheckTx` (#561))

package mocks

import (
	context "context"

	types "github.com/cosmos/cosmos-sdk/types"
	mock "github.com/stretchr/testify/mock"
)

// DistributionKeeper is an autogenerated mock type for the DistributionKeeper type
type DistributionKeeper struct {
	mock.Mock
}

// GetPreviousProposerConsAddr provides a mock function with given fields: ctx
func (_m *DistributionKeeper) GetPreviousProposerConsAddr(ctx context.Context) (types.ConsAddress, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousProposerConsAddr")
	}

	var r0 types.ConsAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (types.ConsAddress, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) types.ConsAddress); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.ConsAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDistributionKeeper creates a new instance of DistributionKeeper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDistributionKeeper(t interface {
	mock.TestingT
	Cleanup(func())
},
) *DistributionKeeper {
	mock := &DistributionKeeper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
