---
project_name: block-sdk

release:
  github:
    owner: skip-mev
    name: block-sdk
  prerelease: true

builds:
  - skip: true

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: false
  use: 'github'

checksum:
  disable: false

source:
  enabled: true
