queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>1"
      - base=main
      - label=A:automerge
    merge_conditions:
      - "#approved-reviews-by>1"
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})
      {{ body }}

pull_request_rules:
  - name: backport patches to v1.x.x branch
    conditions:
      - base=main
    actions:
      backport:
        branches:
          - release/v1.x.x
  - name: backport patches to v2.x.x branch
    conditions:
      - base=main
    actions:
      backport:
        branches:
          - release/v2.x.x
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
