// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package blocksdkv1

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Lane                 protoreflect.MessageDescriptor
	fd_Lane_id              protoreflect.FieldDescriptor
	fd_Lane_max_block_space protoreflect.FieldDescriptor
	fd_Lane_order           protoreflect.FieldDescriptor
)

func init() {
	file_sdk_blocksdk_v1_blocksdk_proto_init()
	md_Lane = File_sdk_blocksdk_v1_blocksdk_proto.Messages().ByName("Lane")
	fd_Lane_id = md_Lane.Fields().ByName("id")
	fd_Lane_max_block_space = md_Lane.Fields().ByName("max_block_space")
	fd_Lane_order = md_Lane.Fields().ByName("order")
}

var _ protoreflect.Message = (*fastReflection_Lane)(nil)

type fastReflection_Lane Lane

func (x *Lane) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Lane)(x)
}

func (x *Lane) slowProtoReflect() protoreflect.Message {
	mi := &file_sdk_blocksdk_v1_blocksdk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Lane_messageType fastReflection_Lane_messageType
var _ protoreflect.MessageType = fastReflection_Lane_messageType{}

type fastReflection_Lane_messageType struct{}

func (x fastReflection_Lane_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Lane)(nil)
}
func (x fastReflection_Lane_messageType) New() protoreflect.Message {
	return new(fastReflection_Lane)
}
func (x fastReflection_Lane_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Lane
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Lane) Descriptor() protoreflect.MessageDescriptor {
	return md_Lane
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Lane) Type() protoreflect.MessageType {
	return _fastReflection_Lane_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Lane) New() protoreflect.Message {
	return new(fastReflection_Lane)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Lane) Interface() protoreflect.ProtoMessage {
	return (*Lane)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Lane) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != "" {
		value := protoreflect.ValueOfString(x.Id)
		if !f(fd_Lane_id, value) {
			return
		}
	}
	if x.MaxBlockSpace != "" {
		value := protoreflect.ValueOfString(x.MaxBlockSpace)
		if !f(fd_Lane_max_block_space, value) {
			return
		}
	}
	if x.Order != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Order)
		if !f(fd_Lane_order, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Lane) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "sdk.blocksdk.v1.Lane.id":
		return x.Id != ""
	case "sdk.blocksdk.v1.Lane.max_block_space":
		return x.MaxBlockSpace != ""
	case "sdk.blocksdk.v1.Lane.order":
		return x.Order != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.blocksdk.v1.Lane"))
		}
		panic(fmt.Errorf("message sdk.blocksdk.v1.Lane does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lane) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "sdk.blocksdk.v1.Lane.id":
		x.Id = ""
	case "sdk.blocksdk.v1.Lane.max_block_space":
		x.MaxBlockSpace = ""
	case "sdk.blocksdk.v1.Lane.order":
		x.Order = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.blocksdk.v1.Lane"))
		}
		panic(fmt.Errorf("message sdk.blocksdk.v1.Lane does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Lane) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "sdk.blocksdk.v1.Lane.id":
		value := x.Id
		return protoreflect.ValueOfString(value)
	case "sdk.blocksdk.v1.Lane.max_block_space":
		value := x.MaxBlockSpace
		return protoreflect.ValueOfString(value)
	case "sdk.blocksdk.v1.Lane.order":
		value := x.Order
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.blocksdk.v1.Lane"))
		}
		panic(fmt.Errorf("message sdk.blocksdk.v1.Lane does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lane) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "sdk.blocksdk.v1.Lane.id":
		x.Id = value.Interface().(string)
	case "sdk.blocksdk.v1.Lane.max_block_space":
		x.MaxBlockSpace = value.Interface().(string)
	case "sdk.blocksdk.v1.Lane.order":
		x.Order = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.blocksdk.v1.Lane"))
		}
		panic(fmt.Errorf("message sdk.blocksdk.v1.Lane does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lane) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.blocksdk.v1.Lane.id":
		panic(fmt.Errorf("field id of message sdk.blocksdk.v1.Lane is not mutable"))
	case "sdk.blocksdk.v1.Lane.max_block_space":
		panic(fmt.Errorf("field max_block_space of message sdk.blocksdk.v1.Lane is not mutable"))
	case "sdk.blocksdk.v1.Lane.order":
		panic(fmt.Errorf("field order of message sdk.blocksdk.v1.Lane is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.blocksdk.v1.Lane"))
		}
		panic(fmt.Errorf("message sdk.blocksdk.v1.Lane does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Lane) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "sdk.blocksdk.v1.Lane.id":
		return protoreflect.ValueOfString("")
	case "sdk.blocksdk.v1.Lane.max_block_space":
		return protoreflect.ValueOfString("")
	case "sdk.blocksdk.v1.Lane.order":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: sdk.blocksdk.v1.Lane"))
		}
		panic(fmt.Errorf("message sdk.blocksdk.v1.Lane does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Lane) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in sdk.blocksdk.v1.Lane", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Lane) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Lane) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Lane) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Lane) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Lane)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Id)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MaxBlockSpace)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Order != 0 {
			n += 1 + runtime.Sov(uint64(x.Order))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Lane)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Order != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Order))
			i--
			dAtA[i] = 0x18
		}
		if len(x.MaxBlockSpace) > 0 {
			i -= len(x.MaxBlockSpace)
			copy(dAtA[i:], x.MaxBlockSpace)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaxBlockSpace)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Id) > 0 {
			i -= len(x.Id)
			copy(dAtA[i:], x.Id)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Id)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Lane)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Lane: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Lane: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Id = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxBlockSpace", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaxBlockSpace = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Order", wireType)
				}
				x.Order = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Order |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: sdk/blocksdk/v1/blocksdk.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lane defines a block-sdk lane and its associated parameters.  Only the
// parameters that are critical to consensus are stored on-chain in this object.
// The other associated configuration for a lane can be set and stored locally,
// per-validator.
type Lane struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the unique identifier of a Lane.  Maps to a block-sdk laneName.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// max_block_space defines the relative percentage of block space that can be
	// used by this lane. NOTE: If this is set to zero, then there is no limit
	// on the number of transactions that can be included in the block for this
	// lane (up to maxTxBytes as provided by the request). This is useful for the
	// default lane.
	MaxBlockSpace string `protobuf:"bytes,2,opt,name=max_block_space,json=maxBlockSpace,proto3" json:"max_block_space,omitempty"`
	// order is the priority ordering of the Lane when processed in
	// PrepareProposal and ProcessProposal. Lane orders should be set in order of
	// priority starting from 0, monotonically increasing and non-overlapping. A
	// lane with a lower order value will have a higher priority over a lane with
	// a higher order value.  For example, if LaneA has priority of 0 and LaneB
	// has a priority of 1, LaneA has priority over LaneB.
	Order uint64 `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *Lane) Reset() {
	*x = Lane{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sdk_blocksdk_v1_blocksdk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lane) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lane) ProtoMessage() {}

// Deprecated: Use Lane.ProtoReflect.Descriptor instead.
func (*Lane) Descriptor() ([]byte, []int) {
	return file_sdk_blocksdk_v1_blocksdk_proto_rawDescGZIP(), []int{0}
}

func (x *Lane) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lane) GetMaxBlockSpace() string {
	if x != nil {
		return x.MaxBlockSpace
	}
	return ""
}

func (x *Lane) GetOrder() uint64 {
	if x != nil {
		return x.Order
	}
	return 0
}

var File_sdk_blocksdk_v1_blocksdk_proto protoreflect.FileDescriptor

var file_sdk_blocksdk_v1_blocksdk_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x64, 0x6b, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x73, 0x64, 0x6b, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x2e, 0x76,
	0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61,
	0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x04, 0x4c, 0x61, 0x6e, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x5e,
	0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x36, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f,
	0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61,
	0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xd2, 0xb4, 0x2d, 0x0a,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x44, 0x65, 0x63, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52,
	0x0d, 0x6d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x42, 0xaf, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x64, 0x6b,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x2e, 0x76, 0x31, 0x42, 0x0d, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x64, 0x6b, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x2f, 0x76, 0x31, 0x3b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x42, 0x58,
	0xaa, 0x02, 0x0f, 0x53, 0x64, 0x6b, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64, 0x6b, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x0f, 0x53, 0x64, 0x6b, 0x5c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x64,
	0x6b, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1b, 0x53, 0x64, 0x6b, 0x5c, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x64, 0x6b, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x11, 0x53, 0x64, 0x6b, 0x3a, 0x3a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x64, 0x6b, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sdk_blocksdk_v1_blocksdk_proto_rawDescOnce sync.Once
	file_sdk_blocksdk_v1_blocksdk_proto_rawDescData = file_sdk_blocksdk_v1_blocksdk_proto_rawDesc
)

func file_sdk_blocksdk_v1_blocksdk_proto_rawDescGZIP() []byte {
	file_sdk_blocksdk_v1_blocksdk_proto_rawDescOnce.Do(func() {
		file_sdk_blocksdk_v1_blocksdk_proto_rawDescData = protoimpl.X.CompressGZIP(file_sdk_blocksdk_v1_blocksdk_proto_rawDescData)
	})
	return file_sdk_blocksdk_v1_blocksdk_proto_rawDescData
}

var file_sdk_blocksdk_v1_blocksdk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_blocksdk_v1_blocksdk_proto_goTypes = []interface{}{
	(*Lane)(nil), // 0: sdk.blocksdk.v1.Lane
}
var file_sdk_blocksdk_v1_blocksdk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sdk_blocksdk_v1_blocksdk_proto_init() }
func file_sdk_blocksdk_v1_blocksdk_proto_init() {
	if File_sdk_blocksdk_v1_blocksdk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sdk_blocksdk_v1_blocksdk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lane); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sdk_blocksdk_v1_blocksdk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_blocksdk_v1_blocksdk_proto_goTypes,
		DependencyIndexes: file_sdk_blocksdk_v1_blocksdk_proto_depIdxs,
		MessageInfos:      file_sdk_blocksdk_v1_blocksdk_proto_msgTypes,
	}.Build()
	File_sdk_blocksdk_v1_blocksdk_proto = out.File
	file_sdk_blocksdk_v1_blocksdk_proto_rawDesc = nil
	file_sdk_blocksdk_v1_blocksdk_proto_goTypes = nil
	file_sdk_blocksdk_v1_blocksdk_proto_depIdxs = nil
}
