name: 'build-docs'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger mintlify workflow
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DOCS_CHILDREN_ACTIONS_TRIGGER_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'mintlify-onboarding',
              repo: 'skip',
              workflow_id: 'mintlify-action.yml',
              ref: 'main',
            });
